python run.py LD
python run.py LL
python run.py LT
python run.py MC
python run.py MS
python run.py NJ
python run.py OW
python run.py RS
python run.py SE
python run.py SJ
python run.py SL
python run.py TB
python run.py TC
python run.py TH
python run.py WE
python run.py WM
